[package]
name = "tls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.3"
byteorder = "1.4.3"
hkdf = "0.12.3"
rand = "0.8.5"
sha2 = "0.10.8"
x25519-dalek = "2.0.0"
